root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  en/latest: community-docs/community-docs-home
  en/latest/01-introduction: community-docs/community-docs-introduction  
  en/latest/02-installation: community-docs/community-docs-installation
  en/latest/03-using-the-graphical-user-interface: community-docs/community-docs-using-the-graphical-user-interface
